Make the Rannuncarpus place directional blocks facing itself.
Vazkii/Botania pull request #3448
Opened 2020-09-06 21:21 UTC by eutropius225

![Rannuncarpus having placed skulls correctly.](https://user-images.githubusercontent.com/11538216/92335407-8ecc5700-f08e-11ea-9112-c7614250a658.png)
![Rannuncarpus having placed chests correctly.](https://user-images.githubusercontent.com/11538216/92335409-8ffd8400-f08e-11ea-8937-6b40ec913060.png)
![Rannuncarpus having placed dispensers correctly.](https://user-images.githubusercontent.com/11538216/92335411-912eb100-f08e-11ea-9d7e-b63604192dea.png)

2020-09-07 16:51 UTC, williewillus commented
Is there a particular application you have in mind for this?

2020-09-22 06:08 UTC, eutropius225 commented
Not specifically, but perhaps this could be used to have the rannuncarpus build more sophisticated things, such as contraptions using pistons or dispensers.

Beside that, having the placement direction properly face the rannuncarpus is a lot more logical than it just being random.

2020-09-22 14:47 UTC, Alwinfy requested changes
Remember to document changes :wacko:

2020-10-20 22:56 UTC, Alwinfy approved these changes

2020-10-21 00:18 UTC, merged