You can't see it, but I'm making a very angry face right now
Vazkii/Botania pull request #3531
Opened 2020-11-27 19:24 UTC by Yoghurt4C

changes:
-updated loom to shorten compile time (and enlarge logspam)
-move renderer registration out of the modelappender (fixes https://github.com/williewillus/botania-fabric-issues/issues/28
-added hard dependencies to fabric.mod.json

2020-11-27 19:25 UTC, williewillus requested changes
angerypotato

2020-11-27 19:25 UTC, williewillus commented on src/main/resources/fabric.mod.json
> +    "patchouli": "*"
minecraft  to 1.16.3 and fapi to the one I use in build.gradle

2020-11-27 21:38 UTC, Yoghurt4C commented
![image](https://user-images.githubusercontent.com/11313954/100485685-14055c00-3112-11eb-9299-3de80600c9ec.png)

2020-11-27 21:42 UTC, Alwinfy commented
dibs on the water-type

On Fri, Nov 27, 2020 at 3:39 PM Yoghurt4C <notifications@github.com> wrote:

> [image: image]
> <https://user-images.githubusercontent.com/11313954/100485685-14055c00-3112-11eb-9299-3de80600c9ec.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Vazkii/Botania/pull/3531#issuecomment-734995305>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE3ZWB3QVGI7VOLSBICXNJDSSAL73ANCNFSM4UFHRJNQ>
> .
>

2020-11-29 04:15 UTC, williewillus commented
Can you make the same lightning changes on forge?

2020-11-29 04:15 UTC, merged