Rearrange Categories of Lexica Botania
Vazkii/Botania pull request #3723
Opened 2021-04-30 19:21 UTC by DasGerippe

Rearranged the categories of the Lexica Botania since they were without logical order (except for Basics being first and Challanges being last).

The order I had in mind is:
- Basics
- Mana Manipulation
- Generating Flora
- Functional Flora
- Tools (Mystical Items)
- Devices (Natural Apparatus)
- Baubles
- Misc
- Alfhomancy
- Ender
- Challanges

Feel free to further adjust the order.

2021-05-02 14:29 UTC, Hubry commented
Uh, did I break something in Patchouli that made them go unsorted? Oops

2021-05-02 14:39 UTC, Hubry requested changes
The original order from 1.12 and before was:

- Basics
- Mana
- Generating Flowers
- Functional Flowers
- Devices
- Tools
- Baubles
- Ender
- Alfhomancy
- Misc

Can you tweak it to exactly reproduce this? I'll merge afterwards.

2021-05-03 01:07 UTC, DasGerippe commented
Sure, done. Something else just popped into my mind: Since Challanges probably always should be the last category, do we set it's sortNumber to something very high, so categories of addons wont be after challanges? Or does the addon dev have to worry about this?

2021-05-03 08:21 UTC, Hubry commented
Not a bad idea, actually.

2021-05-03 18:05 UTC, Hubry approved these changes

2021-05-03 19:07 UTC, merged