Update blackHoleTalisman entry
Vazkii/Botania pull request #4146
Opened 2022-08-31 16:29 UTC by Aegide

> if i right click on a chest, the chest open :clueless:

2022-09-01 05:12 UTC, williewillus requested changes

2022-09-01 05:12 UTC, williewillus commented on Xplat/src/main/resources/assets/botania/lang/en_us.json
> +  "botania.page.blackHoleTalisman2": "Any blocks stored in a Talisman can be placed by simply right-clicking with it.$(p)Sneak-right clicking the Talisman on an inventory will dump up to a stack of b
Should be `Sneak right-clicking`, not `Sneak-right clicking`

2022-09-02 21:51 UTC, Aegide commented on Xplat/src/main/resources/assets/botania/lang/en_us.json
> +  "botania.page.blackHoleTalisman2": "Any blocks stored in a Talisman can be placed by simply right-clicking with it.$(p)Sneak-right clicking the Talisman on an inventory will dump up to a stack of b
![image](https://user-images.githubusercontent.com/43409914/188239598-15c17691-df36-484a-9de3-d0935a649706.png)

Then why are there 33 entries that use `Sneak-right clicking` and 0 entries that use `Sneak right-clicking`.

2022-09-03 01:20 UTC, williewillus commented on Xplat/src/main/resources/assets/botania/lang/en_us.json
> +  "botania.page.blackHoleTalisman2": "Any blocks stored in a Talisman can be placed by simply right-clicking with it.$(p)Sneak-right clicking the Talisman on an inventory will dump up to a stack of b
ok, this is fine for now then, though I think that's the wrong version to use.

2022-09-03 01:21 UTC, merged

2022-09-03 08:00 UTC, Aegide commented on Xplat/src/main/resources/assets/botania/lang/en_us.json
> +  "botania.page.blackHoleTalisman2": "Any blocks stored in a Talisman can be placed by simply right-clicking with it.$(p)Sneak-right clicking the Talisman on an inventory will dump up to a stack of b
Yeah true, but I didn't want to go against the standard that was already established.