Fix assignment wtih Charms
Vazkii/Botania pull request #4443
Opened 2023-08-26 08:43 UTC by Shibva

Corrects a slight error wtih charms being put in the necklace slot when it shouldn't (on the basis that curio's have their own slot for charms)

makes it close to "parallel" features present in Curios

- Creates a Charm slot located in the main hand section
- Created a tag under hand/charm
- Migrate Diva Charm and Goddess Charm from necklace tag to charm tag

2023-08-26 19:18 UTC, williewillus commented
You need to do the change in the datagen instead of manually editing files in the `generated` folder

2023-08-26 19:18 UTC, williewillus commented
Also, please target 1.20, I'll pick back to 1.19.2

2023-08-26 19:19 UTC, williewillus requested changes
as above

2023-08-26 19:48 UTC, Shibva commented
Noted

I'll do that when I have the chance

2023-08-27 03:53 UTC, Shibva commented
> You need to do the change in the datagen instead of manually editing files in the `generated` folder

Can you clarify what you mean by datagen? I'm not familular with this workspace

2023-08-27 05:41 UTC, williewillus commented
Change the code somewhere here https://github.com/VazkiiMods/Botania/blob/1.20.x/Fabric/src/main/java/vazkii/botania/fabric/data/FabricItemTagProvider.java#L63

then run the `:Fabric:runFabricDatagen` Gradle task to regenerate the json files

2023-08-28 04:36 UTC, Shibva commented
closing to make a proper pull merge

2023-08-28 04:36 UTC, closed without merging